# Generated by Django 4.0.5 on 2022-06-09 02:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questionapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
